# Generated by Django 5.2.8 on 2025-12-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateField(),
        ),
    ]
