# Generated by Django 5.2.8 on 2025-12-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('active', 'Active'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('canceled', 'Canceled')], default='requested', max_length=30),
        ),
    ]
